# Do not double-build branches and PRs from this repo
if: repo != head_repo

language: android
android:
  components:
    - build-tools-26.0.2
    - build-tools-29.0.2
    - android-29

before_install:
    - yes | sdkmanager "platforms;android-29"

notifications:
  email:
    on_success: never
